// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalkMate.Infrastructure.Data;

#nullable disable

namespace TalkMate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129111857_initialDB_HTSC14040908")]
    partial class initialDB_HTSC14040908
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalkMate.Domain.Entities.ChatResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("ChatResponses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c95a607-5c8d-4391-8b64-4f9a2e70dd3a"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 5, 10, 0, DateTimeKind.Utc),
                            MessageId = new Guid("2227d6a7-e0fe-45ee-8a36-e6c0b42bfe97"),
                            ResponseText = "It seems you're stressed. Take a deep breath 🌿"
                        });
                });

            modelBuilder.Entity("TalkMate.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2227d6a7-e0fe-45ee-8a36-e6c0b42bfe97"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 5, 0, 0, DateTimeKind.Utc),
                            Text = "Feeling a bit stressed about work lately.",
                            UserId = new Guid("d0fe9715-2043-4d9d-9949-a7e485ace584")
                        });
                });

            modelBuilder.Entity("TalkMate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0fe9715-2043-4d9d-9949-a7e485ace584"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo User"
                        });
                });

            modelBuilder.Entity("TalkMate.Domain.Entities.ChatResponse", b =>
                {
                    b.HasOne("TalkMate.Domain.Entities.Message", "Message")
                        .WithOne("Response")
                        .HasForeignKey("TalkMate.Domain.Entities.ChatResponse", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TalkMate.Domain.Entities.Message", b =>
                {
                    b.HasOne("TalkMate.Domain.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalkMate.Domain.Entities.Message", b =>
                {
                    b.Navigation("Response");
                });

            modelBuilder.Entity("TalkMate.Domain.Entities.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
